### ISSUE TITLE
DDI_EBEYE xml files

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/datadiscoveryindex#13]
I have made two DDI example files for PX and MetaboLights.

[check them at here] (https://github.com/PSI-PROXI/datadiscoveryindex/commit/c16430ca0098044c0244c7701f5ae943846fdf32)

I am still working on these issues:
1. config files
2. tags for each entry

**Comment by ypriverol** [comment]
@baimingze it would be great to check the schema of the xml by external services. I was reading this information https://www.ebi.ac.uk/seqdb/confluence/display/EXT/EBI+Search+domain+information+template and we can combine it with the one we already define for proteomeXchange.

**Comment by baimingze** [comment]
the draft configure file is [here](https://github.com/PSI-PROXI/datadiscoveryindex/commit/cfb76b76e31cca7ae893e750fc1a5801b75ab1a0)

**Comment by ypriverol** [comment]
@baimingze I finish the first prototype of the ddi XML datadiscoveryindex/docs/EBEYE files/ddi.xml, please a final look and close the issue if you are agree.

**Comment by ypriverol** [comment]
This is already done. I will close this issue.
