### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Leprevost** [BD2K-DDI/datadiscoveryindex#19]
The  whole idea of the project looks very interesting and the mechanics of the website is great. I found easy to navigate between the pages and the website is organized in a logical way. Below are a few points that I believe can be enhanced to make the user experience even better.

## Responsiveness

I noticed that the home page graphs sometimes break when I change the screen size. I believe this can be fixed with some simple adjustments on the CSS (see example below).

![ddi-ipad](https://cloud.githubusercontent.com/assets/403705/8409562/a616bbf0-1e46-11e5-8235-44c6943cc802.png)

I also noticed that some text also escaped the boxes while changing the screen size.

## Search results

The search results are organized in colored boxes with information inside, like [here](http://wwwdev.ebi.ac.uk/Tools/ddi/browse.html#/search?q=analysis%20AND%20omics_type:%22Proteomics%22) for example.

I think that if you add a little space between the items inside the box (project description, organism, made public), it could improve the reading, as this page can be full with text. Also, the repository name seems to be there without any header (between 'organism' and 'made public').

# Links between datasets

At some point, it will become even more common to see large projects where people use more than one approach to study some biological phenomena. Having that in mind, it should be easy for the user to connect those datasets from the same project without the need for searching them using the author name or the project name. I think it could be useful if the datasets from the same projects could have some sort of link between them, making easy to navigate from one to another and, more importantly, making easy to 'connect' those results.

**Comment by baimingze** [comment]
@Leprevost , thank you for your valuable comments, most of them have been fixed, except the last one. We will take the last one in consider in the future version.
